---
- hosts: all
  become: yes
  tags: [ dotfiles ]

  tasks:
    - name: Cloning
      git:
        repo: https://github.com/oxodao/dotfiles.git
        dest: /opt/dotfiles
      become: no

    - name: Creating folders
      file:
        dest: "/home/{{ansible_user}}/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      with_items: [ ".config", ".config/alacritty", "Documents", "Images", "Musiques", "Vidéos", "Téléchargements" ]
      become: no

    - name: Creating memo and .zshrc.custom
      file:
        path: "/home/{{ ansible_user }}/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: touch
        mode: '0600'
      with_items: [ ".memo", ".zshrc.custom" ]
      become: no

    - name: Download zsh installer
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/zsh-installer.sh
        mode: '0777'

    - name: Execute the zsh-installer.sh
      shell: /tmp/zsh-installer.sh --unattended
      become: no

    - name: Remove the zsh-installer.sh
      file: 
        path: /tmp/zsh-installer.sh
        state: absent

    - name: Remove the generated zshrc
      file: 
        path: "/home/{{ ansible_user }}/.zshrc"
        state: absent

    - name: Installing mattboll's zsh theme
      copy:
        src: files/mattboll.zsh-theme
        dest: "/home/{{ ansible_user }}/.oh-my-zsh/themes/mattboll.zsh-theme"

    - name: Symlinking all the things
      file:
        src: "/opt/dotfiles/{{ item.src }}"
        dest: "/home/{{ ansible_user }}/{{ item.dest }}"
        state: link
      with_items: "{{ mappings }}"
      become: no

    - name: Checking if there is a resources file for this machine
      stat:
        path: "/opt/dotfiles/resources.{{ inventory_hostname }}"
      register: res
      become: no

    - name: Symlinking resources file
      file:
        src: "/opt/dotfiles/resources.{{ inventory_hostname }}"
        dest: "/home/{{ ansible_user }}/.Xresources.{{ inventory_hostname}}"
        state: link
        mode: '0755'
      when: res.stat.exists
      become: no

    - name: xdg dirs
      command: xdg-user-dirs-update
      become: no

    - name: Setting zsh by default
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh
